services:

  av_car_description:
    image: "av_car_description:latest"
    container_name: av_car_description
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev/shm:/dev/shm"
      - "/etc/localtime:/etc/localtime:ro"

  av_dbw:
    image: "av_dbw:latest"
    container_name: av_dbw
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/etc/localtime:/etc/localtime:ro"

  av_imu:
    image: "av_imu:latest"
    container_name: av_imu
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev/shm:/dev/shm"
      - "/dev/imu-6:/dev/imu-6"
      - "/etc/localtime:/etc/localtime:ro"

  av_gps:
    image: "av_gps:latest"
    container_name: av_gps
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev/shm:/dev/shm"
      - "/etc/localtime:/etc/localtime:ro"

  av_ouster:
    image: "av_ouster:latest"
    container_name: av_ouster
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev/shm:/dev/shm"
      - "/etc/localtime:/etc/localtime:ro"

  av_velodyne:
    image: "av_velodyne:latest"
    container_name: av_velodyne
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev/shm:/dev/shm"
      - "/etc/localtime:/etc/localtime:ro"

  av_camera:
    image: "av_camera:latest"
    container_name: av_camera
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev/shm:/dev/shm"
      - "/etc/localtime:/etc/localtime:ro"

include:
  - dev_radar_compose.yaml
