services:

  av_bms:
    image: "av_bms:latest"
    container_name: av_bms
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_camera:
    image: "av_camera:latest"
    container_name: av_camera
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_car_description:
    image: "av_car_description:latest"
    container_name: av_car_description
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_dbw:
    image: "av_dbw:latest"
    container_name: av_dbw
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_gps:
    image: "av_gps:latest"
    container_name: av_gps
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_imu:
    image: "av_imu:latest"
    container_name: av_imu
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_ntrip_client:
    image: "ghcr.io/ipab-rad/av_camera:latest"
    container_name: av_ntrip_client
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"