services:

  av_car_description:
    image: "av_car_description:latest"
    container_name: av_car_description
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_dbw:
    image: "av_dbw:latest"
    container_name: av_dbw
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_imu:
    image: "av_imu:latest"
    container_name: av_imu
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_gps:
    image: "av_gps:latest"
    container_name: av_gps
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_ouster:
    image: "av_ouster:latest"
    command: sh -c "ros2 launch av_ouster_launch av_ouster.launch.xml ros_time:='True'"
    container_name: av_ouster
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_velodyne:
    image: "av_velodyne:latest"
    command: sh -c "ros2 launch av_velodyne_launch av_velodyne.launch.xml ros_time:='True'"
    container_name: av_velodyne
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_camera:
    image: "av_camera:latest"
    container_name: av_camera
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_camera_trigger:
    image: "av_camera_trigger:latest"
    command: sh -c "sleep 13 && ros2 launch av_camera_trigger av_camera_trigger.launch.xml"
    container_name: av_camera_trigger
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - av_camera

include:
  - local_radar_compose.yaml
