services:
  cameras_driver:
    image: "av_camera_launch_humble:latest"

  dbw_driver:
    image: "av_dbw_launch:latest"

  aw_radar_bridge_humble:
    image: "aw_radar_bridge_humble:latest"

  imu_driver:
    image: "imu_humble:latest"

  car_description:
    image: "car_description_humble:latest"
  
  gps_driver:
    image: "av_novatel_launch_humble"