services:

  car_description:
    image: "car_description_humble:latest"
    container_name: car_description_humble
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev/shm:/dev/shm"      

  dbw_dataspeed_driver:
    image: "av_dbw_launch:latest"
    container_name: av_dbw_launch
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev/shm:/dev/shm"
      - "/dev/bus/usb:/dev/bus/usb"

  imu_microstrain_driver:
    image: "imu_humble:latest"
    container_name: imu_humble
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev/shm:/dev/shm" 
      - "/dev/imu-6:/dev/imu-front"
  
  gps_novatel_driver:
    image: "av_novatel_launch_humble:latest"
    container_name: av_novatel_launch_humble
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev/shm:/dev/shm"  

  lidar_ouster_driver:
    image: "av_ouster_launch_humble:latest"
    container_name: av_ouster_launch_humble
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev/shm:/dev/shm"  

  lidars_velodyne_driver:
    image: "av_velodyne_launch_humble:latest"
    container_name: av_velodyne_launch_humble
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev/shm:/dev/shm"

  cameras_flir_driver:
    image: "av_camera_launch_humble:latest"
    container_name: av_camera_launch_humble
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev/shm:/dev/shm"
    