services:

  av_bms:
    image: "ghcr.io/ipab-rad/av_bms:0.0.1"
    container_name: av_bms
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_car_description:
    image: "ghcr.io/ipab-rad/av_car_description:2.0.0"
    container_name: av_car_description
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_dbw:
    image: "ghcr.io/ipab-rad/av_dbw:1.1.0"
    container_name: av_dbw
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_imu:
    image: "ghcr.io/ipab-rad/av_imu:2.1.0"
    container_name: av_imu
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_gps:
    image: "ghcr.io/ipab-rad/av_gps:1.3.1"
    container_name: av_gps
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_ouster:
    image: "ghcr.io/ipab-rad/av_ouster:2.4.1"
    container_name: av_ouster
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_velodyne:
    image: "ghcr.io/ipab-rad/av_velodyne:1.3.0"
    container_name: av_velodyne
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_camera:
    image: "ghcr.io/ipab-rad/av_camera:2.0.1"
    container_name: av_camera
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_camera_trigger:
    image: "ghcr.io/ipab-rad/av_camera_trigger:2.0.0"
    command: sh -c "sleep 13 && ros2 launch av_camera_trigger av_camera_trigger.launch.xml"
    container_name: av_camera_trigger
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - av_camera

include:
  - radar_compose.yaml
