services:

  dbw_dataspeed_driver:
    image: "av_dbw_launch:latest"

  imu_microstrain_driver:
    image: "imu_humble:latest"

  car_description:
    image: "car_description_humble:latest"
  
  gps_novatel_driver:
    image: "av_novatel_launch_humble:latest"

  lidar_ouster_driver:
    image: "av_ouster_launch_humble:latest"
  
  lidars_velodyne_driver:
    image: "av_velodyne_launch_humble:latest"

  cameras_flir_driver:
    image: "av_camera_launch_humble:latest"
    