services:

  av_bms:
    image: "ghcr.io/ipab-rad/av_bms:0.0.1"
    container_name: av_bms
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_camera:
    image: "ghcr.io/ipab-rad/av_camera:3.0.0"
    container_name: av_camera
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_car_description:
    image: "ghcr.io/ipab-rad/av_car_description:3.0.0"
    container_name: av_car_description
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_dbw:
    image: "ghcr.io/ipab-rad/av_dbw:1.1.0"
    container_name: av_dbw
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_gps:
    image: "ghcr.io/ipab-rad/av_gps:1.3.1"
    container_name: av_gps
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_imu:
    image: "ghcr.io/ipab-rad/av_imu:2.1.0"
    container_name: av_imu
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_lidar:
    image: "ghcr.io/ipab-rad/av_lidar:1.0.0"
    container_name: av_lidar
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_ntrip_client:
    image: "ghcr.io/ipab-rad/av_ntrip_client:1.2.0"
    container_name: av_ntrip_client
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"
