services:

  av_car_description:
    image: "ghcr.io/ipab-rad/av_car_description:1.3.0"
    container_name: av_car_description
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_dbw:
    image: "ghcr.io/ipab-rad/av_dbw:1.1.0"
    container_name: av_dbw
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_imu:
    image: "ghcr.io/ipab-rad/av_imu:1.2.1"
    container_name: av_imu
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_gps:
    image: "ghcr.io/ipab-rad/av_gps:1.2.0"
    container_name: av_gps
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_ouster:
    image: "ghcr.io/ipab-rad/av_ouster:2.1.0"
    container_name: av_ouster
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_velodyne:
    image: "ghcr.io/ipab-rad/av_velodyne:1.2.0"
    container_name: av_velodyne
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"

  av_camera:
    image: "ghcr.io/ipab-rad/av_camera:1.0.0"
    container_name: av_camera
    network_mode: "host"
    privileged: true
    volumes:
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "/etc/localtime:/etc/localtime:ro"
include:
  - radar_compose.yaml
